#!/usr/bin/env python3

from __future__ import print_function
import sys

lines = sys.stdin.readlines()

l1 = []
l2 = []
l3 = []
l4 = []
l5 = []
l6 = []
l7 = []


for line in lines:
  num = line.split(':')[0]
  if "PriMeta" in line or "PriLatestTargets" in line or "SecMeta" in line:
    l1.append(num)
  elif "!KU( sign(<pk(~root_seckey" in line:
    l2.append(num)
  elif "root_sec" in line:
    l3.append(num)
  elif "timestamp" in line or "h(~" in line:
    l4.append(num)
  elif "~snapshot" in line or "~ss" in line:
    l5.append(num)
  elif "targets" in line or "h(~pri" in line or "h(~sec" in line:
    l6.append(num)
  else:
    l7.append(num)

ranked = l1 + l2  + l3 + l4 + l5 + l6 + l7

for i in ranked:
  print(i)